# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: alphanics.github.io
title: alphanics VLog
description: programming
url: https://alphanics.github.io
profile_url: /assets/imgs/me.jpg
email: changkuktai@gmail.com

# Handling Reading
exclude: ['node_modules', 'vendor'] # Remove comment at local evelopment mode

# markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 10
